@startuml
title Система автоматического тестирования: диаграмма последовательности
participant Учитель
participant Тестирование
participant Ученик
activate Учитель

Учитель -> Тестирование: Составляет тестирование
activate Тестирование
Учитель -> Тестирование: Запускает тестирование
Учитель -> Ученик: Предоставляет тестирование
deactivate Учитель
activate Ученик
Ученик -> Тестирование:Приступает к выполнению
Ученик -> Тестирование:Выполняет тестирование
deactivate Тестирование
Ученик -> Учитель:Сообщает о выполнении тестирования
deactivate Ученик
activate Учитель
Тестирование -> Учитель:Проверка ответов
activate Тестирование
Тестирование -> Учитель:Корректное выполнение задания
Тестирование -> Учитель:Выдает ответы
Учитель -> Тестирование:Принимает тестирование
deactivate Учитель
deactivate Тестирование
@enduml

@startuml
left to right direction
title Система автоматического тестирования: диаграмма развертывания
database Тестировани
node ПК_Ученик
node ПК_Учитель
node Система_контроля

ПК_Ученик - Тестировани: Выполняют
ПК_Учитель - Тестировани: Создает
ПК_Учитель - Система_контроля: Проверка выполнения тестирования
Система_контроля - Тестировани
@enduml