@startuml
class Учитель{
+Паспортные данные
+ФИО
+Должность
Запуск теста()

}

class Задание{
+Номер варианта
+ФИО выполняющего задание
+Время на выполнение
+Задания
}

class Ученик{
+ФИО
+Должность
Выполнение задания()
Дача ответов()
}

class СтатусЗадания{
+Номер задания
+Статус задания
}

class Выполнено{
+Даны ответы на задания
}

Учитель --> Задание:Выдает
Ученик --> Задание:Выполняет
Ученик --> СтатусЗадания:Изменяет статус
Учитель -- СтатусЗадания:Проверяет выполнение задания
СтатусЗадания --> Выполнено
Задание --> Выполнено
Выполнено --> ВыдачаОтветов
@enduml

@startuml
left to right direction
title Система автоматического тестирования
actor Учитель
actor Ученик
rectangle Система {
Учитель -- (Запуск тестирования)
(Запуск тестирования) ..>(Выполнять задание):<<include>>
(Запуск тестирования) ..> (Отслеживание выполнения):<<include>>
(Запуск тестирования) ..> (Отслеживать результатов):<<include>>
Ученик -- (Выполнять задание)
(Выполнять задание) ..> (Выдача ответов):<<include>>
(Отслеживание выполнения) ..> (Выдача ответов):<<include>>
(Отслеживать результатов) ..> (Выдача ответов):<<include>>
}
@enduml