@startuml
left to right direction
actor клиент
actor Ozon
rectangle Постомат {
клиент -- (Получить товар)
(Проверка номена заказа)
(Проверка наличия заявки на возврат)
клиент -- (Возврат)
(Получить товар) .> (Проверка номена заказа) : include
(Возврат) .> (Проверка наличия заявки на возврат) : include
Ozon -- (Проверка работоспособности)
}
@enduml